import { Job } from './class.wh';


export const JOBS: Job[] = [

  {
    name: 'Wells Fargo',
    title: 'Enterprise UI/UX Specialist ',
    id: 'wf',
    last: false,
    logo: 'assets/img/WellsFargo.svg',
    details: 'cool things',
    startdate: '10/13/2016',
    enddate: '10/13/2016',
    DevTime: 15,
    DesignTime: 85,
  },
  {
    name: 'Boeing',
    title: 'Enterprise UI/UX Specialist ',
    id: 'bo',
    last: false,
    logo: 'assets/img/Att-logo.svg',
    details: 'cool things',
    startdate: '10/13/2016',
    enddate: '10/13/2016',
    DevTime: 50,
    DesignTime: 50,
  },
  {
    name: 'Comcast',
    title: 'Level 4 Specialist / Sr. UI/UX Designer',
    id: 'co',
    last: false,
    logo: 'assets/img/Att-logo.svg',
    details: 'cool things',
    startdate: '10/13/2016',
    enddate: '10/13/2016',
    DevTime: 50,
    DesignTime: 50,
  },
  {
    name: 'Dell',
    title: 'UI/UX Specialist',
    id: 'de',
    last: false,
    logo: 'assets/img/Att-logo.svg',
    details: 'cool things',
    startdate: '10/13/2016',
    enddate: '10/13/2016',
    DevTime: 25,
    DesignTime: 75,
  },
  {
    name: 'AT&T',
    title: 'UI/UX Specialist',
    id: 'at',
    last: false,
    logo: 'assets/img/Att-logo.svg',
    details: 'cool things',
    startdate: '10/13/2016',
    enddate: '10/13/2016',
    DevTime: 75,
    DesignTime: 25,
  },
  {
    name: 'Northrop Grumman',
    title: 'Sr. Web Developer',
    id: 'ng',
    last: false,
    logo: 'assets/img/Att-logo.svg',
    details: 'cool things',
    startdate: '10/13/2016',
    enddate: '10/13/2016',
    DevTime: 50,
    DesignTime: 50,
  },
  {
    name: 'CDC',
    title: 'Sr. Web Developer',
    id: 'cd',
    last: true,
    logo: 'assets/img/Att-logo.svg',
    details: 'cool things',
    startdate: '10/13/2016',
    enddate: '10/13/2016',
    DevTime: 65,
    DesignTime: 55,
  }
];
